### ISSUE TITLE
Dlaczego, jeśli w formularzu $apartment jest nullem, ustawiamy $slots := 0?

### ISSUE THREAD

**Issue by EmilMassey** [SzymonRybicki/simple_booking_system#1]
https://github.com/SzymonRybicki/simple_booking_system/blob/b57ff76b8e9c7b6a77d4fe9e94dcb3358b7b563f/simple_booking_system/src/Form/Modifier/BookingFormModifier.php#L18

**Comment by SzymonRybicki** [comment]
Przypisanie wynika z błędnego pierwszego założenia, które zapomniałem następnie zrefaktoryzować.
Poprawiony kod:
https://github.com/SzymonRybicki/simple_booking_system/commit/e86711e12990ca524db0c870b767b5dc027469c0?fbclid=IwAR1JwHAnrtWTLt4RFWrxTtvjaR5ge1WzLCg8WGK2fMe2rtCKinBF-idGOBU

**Comment by EmilMassey** [comment]
Super, dzięki za wyjaśnienie!
